#!/usr/bin/env python3
"""Build the status dashboard blob served by the firmware.

    build_web.py --version X.Y.Z [--max-gz BYTES] [--html-out PAGE] web/index.html web/logo.svg [OUT.c]

web/index.html is a single self-contained page. In it:
  - <!--LOGO--> is replaced by the logo SVG (inline);
  - %VERSION% by the firmware version;
  - %BRAND_NAME% / %BRAND_TAGLINE% by the provisioned branding (device.env).
The result is lightly minified (comments and indentation only), gzipped
deterministically and written as a C array, with an ETag derived from the
version and the content. The build fails if the gzipped page exceeds --max-gz.
"""
import argparse
import gzip
from html import escape
import hashlib
import pathlib
import re
import sys


def minify(html: str) -> str:
    html = re.sub(r"<!--(?!LOGO).*?-->", "", html, flags=re.S)
    out = []
    for line in html.splitlines():
        s = line.strip()
        if not s:
            continue
        # Whole-line JS/CSS comments only: inline ones may sit inside strings.
        if s.startswith("// ") or (s.startswith("/*") and s.endswith("*/")):
            continue
        out.append(s)
    return "\n".join(out)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", required=True)
    ap.add_argument("--brand-name", default="RTK Base")
    ap.add_argument("--brand-tagline", default="MCU Base Status")
    ap.add_argument("--max-gz", type=int, default=20 * 1024)
    ap.add_argument("html", type=pathlib.Path)
    ap.add_argument("logo", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path, nargs="?")
    ap.add_argument("--html-out", type=pathlib.Path, help="also write the processed page (tools/web_dev.py)")
    args = ap.parse_args()

    logo = args.logo.read_text().strip()
    html = args.html.read_text()
    html = (html.replace("<!--LOGO-->", logo).replace("%VERSION%", args.version)
            .replace("%BRAND_NAME%", escape(args.brand_name)).replace("%BRAND_TAGLINE%", escape(args.brand_tagline)))
    raw = minify(html).encode()
    if args.html_out:
        args.html_out.write_bytes(raw)
    gz = gzip.compress(raw, compresslevel=9, mtime=0)
    etag = f'"{args.version}-{hashlib.sha256(gz).hexdigest()[:8]}"'
    print(f"Dashboard: {len(raw)} bytes, {len(gz)} gzipped, ETag {etag}")
    if len(gz) > args.max_gz:
        sys.exit(f"ERROR: dashboard is {len(gz)} bytes gzipped, limit {args.max_gz}")
    if not args.out:
        return

    lines = ["// Generated by tools/build_web.py from web/. Do not edit.", "#include <stddef.h>",
             "#include <stdint.h>", "",
             'const char web_index_etag[] = "' + etag.replace('"', '\\"') + '";',
             f"const size_t web_index_gz_len = {len(gz)};", "const uint8_t web_index_gz[] = {"]
    for i in range(0, len(gz), 16):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in gz[i:i + 16]) + ",")
    lines += ["};", ""]
    args.out.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
