#!/usr/bin/env python3
"""Generate the TLS trust store compiled into the firmware.

    gen_ca_bundle.py [--min-years N] OUT.c CERT.pem [CERT.pem ...]

Missing files are skipped (e.g. an absent provision/ca.pem).

The build fails if any trust anchor expires within N years (default 5), so
every release forces a look at the trust store long before a root runs out.
The device itself does not enforce the expiry of its trust anchors (see
src/tls.c); this check is what keeps them current.
"""
import argparse
import base64
import datetime
import pathlib
import re
import sys


def der_tlv(data: bytes, pos: int):
    """Return (tag, content_start, content_end) of the DER element at pos."""
    tag = data[pos]
    n = data[pos + 1]
    pos += 2
    if n & 0x80:
        count = n & 0x7F
        n = int.from_bytes(data[pos:pos + count], "big")
        pos += count
    return tag, pos, pos + n


def der_time(data: bytes, pos: int) -> datetime.datetime:
    tag, s, e = der_tlv(data, pos)
    text = data[s:e].decode()
    if tag == 0x17:  # UTCTime YYMMDDHHMMSSZ
        year = int(text[:2])
        text = f"{1900 + year if year >= 50 else 2000 + year}{text[2:]}"
    elif tag != 0x18:  # GeneralizedTime YYYYMMDDHHMMSSZ
        raise ValueError("bad time tag")
    return datetime.datetime.strptime(text, "%Y%m%d%H%M%SZ").replace(tzinfo=datetime.timezone.utc)


def not_after(der: bytes) -> datetime.datetime:
    # Certificate ::= SEQUENCE { tbsCertificate, ... }
    _, cert, _ = der_tlv(der, 0)
    _, pos, _ = der_tlv(der, cert)  # tbsCertificate contents
    if der[pos] == 0xA0:  # [0] version
        pos = der_tlv(der, pos)[2]
    for _ in range(3):  # serialNumber, signature, issuer
        pos = der_tlv(der, pos)[2]
    _, validity, _ = der_tlv(der, pos)
    after = der_tlv(der, validity)[2]  # skip notBefore
    return der_time(der, after)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--min-years", type=float, default=5)
    ap.add_argument("out", type=pathlib.Path)
    ap.add_argument("certs", nargs="+")
    args = ap.parse_args()

    pems = []
    for p in args.certs:
        f = pathlib.Path(p)
        if not f.exists():
            continue
        blocks = re.findall(r"-----BEGIN CERTIFICATE-----.+?-----END CERTIFICATE-----", f.read_text(), re.S)
        if not blocks:
            sys.exit(f"{p}: no PEM certificate found")
        pems += [(f.name, b) for b in blocks]

    now = datetime.datetime.now(datetime.timezone.utc)
    limit = now + datetime.timedelta(days=365.25 * args.min_years)
    short = []
    for name, b in pems:
        body = "".join(b.splitlines()[1:-1])
        expiry = not_after(base64.b64decode(body))
        print(f"TLS trust anchor {name}: expires {expiry:%Y-%m-%d}")
        if expiry < limit:
            short.append(f"{name} expires {expiry:%Y-%m-%d}")
    if short:
        sys.exit(f"ERROR: trust anchor(s) expire within {args.min_years:g} years: {'; '.join(short)}. "
                 "Add the successor roots (and drop the old ones once no server needs them), "
                 "or lower CA_MIN_YEARS deliberately.")

    lines = ["// Generated by tools/gen_ca_bundle.py. Do not edit.", "#include <stddef.h>", "",
             "const char tls_ca_bundle[] ="]
    for name, b in pems:
        lines.append(f"    // {name}")
        lines += [f'    "{l}\\n"' for l in b.splitlines()]
    lines += ["    ;", "const size_t tls_ca_bundle_len = sizeof(tls_ca_bundle);",
              f"const int tls_ca_count = {len(pems)};", ""]
    args.out.write_text("\n".join(lines))
    print(f"TLS trust store: {len(pems)} certificate(s)")


if __name__ == "__main__":
    main()
